version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    # without it only app can connect to db and also docker exec, so no SQL editors and Database Managers.
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=example_postgres
  redis:
    image: redis:7.0.5-alpine
    ports:
    - "6379:6379"
    environment:
      - REDIS_PASSWORD=secret_redis
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/example_postgres?sslmode=disable
      - REDIS_ADDRESS=redis:6379
      - WAIT_HOSTS=postgres:5432, redis:6379
    depends_on:
      - postgres
      - redis
    command: sh -c "/app/wait && /app/start.sh /app/main"