// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"
)

type Article struct {
	ID        int64        `json:"id"`
	Author    string       `json:"author"`
	Headline  string       `json:"headline"`
	Content   string       `json:"content"`
	CreatedAt time.Time    `json:"created_at"`
	EditedAt  sql.NullTime `json:"edited_at"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
