// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetArticle(ctx context.Context, id int64) (Article, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListArticles(ctx context.Context, arg ListArticlesParams) ([]Article, error)
	UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error)
}

var _ Querier = (*Queries)(nil)
